export declare const EN = "en";
export declare const RU = "ru";
export declare const TABLE_ICON: string;
export declare const FOLDER_ICON: string;
export declare const USERS_ICON: string;
export declare const PLAY_ICON: string;
export declare const STAR_ICON: string;
export declare const SITEMAP_ICON: string;
export declare const SIGN_OUT_ICON: string;
export declare const USER_ICON: string;
export declare const ANGLE_DOWN_ICON: string;
export declare const ANGLE_UP_ICON: string;
export declare const TRASH_ICON: string;
export declare const EXCLAMATION_TRIANGLE_ICON: string;
export declare const SEARCH_ICON: string;
export declare const CHECK_ICON: string;
export declare const LIST_ICON: string;
export declare const PLUS_ICON: string;
export declare const CANCEL_ICON: string;
export declare const EDIT_ICON: string;
export declare const LANGUAGE_ICON: string;
export declare const FLAG_ICON: string;
export declare const FILLED_FLAG_ICON: string;
export declare const MONEY_ICON: string;
export declare const DATABASE_ICON: string;
export declare const SHIELD_ICON: string;
export declare const SLIDERS_ICON: string;
export declare const BOX_ICON: string;
export declare const BOLT_ICON: string;
export declare const SYNC_ICON: string;
export declare const STATIC_AVATAR = "https://seeklogo.com/images/W/White_Zombie-logo-5359114AE9-seeklogo.com.png";
export declare const IMAGE_SHAPE: "circle" | "square" | undefined;
export declare const IMAGE_SIZE_XLARGE: "xlarge" | "normal" | "large" | undefined;
export declare const IMAGE_SIZE_LARGE: "xlarge" | "normal" | "large" | undefined;
export declare const IMAGE_SIZE_NORMAL: "xlarge" | "normal" | "large" | undefined;
export declare const SMALL_SIZE: "small";
export declare const TABLE_SIZE: number;
export declare const MOBILE_SIZE: number;
export declare const DESKTOP_SIZE: number;
export declare const ERROR_SEVERITY: "error";
export declare const INFO_SEVERITY: "info";
export declare const WARNING_SEVERITY: "warn";
export declare const SUCCESS_SEVERITY: "success";
export declare const DANGER_SEVERITY: "danger";
export declare const LOGIN_INPUT: string;
export declare const PASSWORD_INPUT: string;
export declare const SUBMIT_INPUT: "submit";
export declare const USERNAME_INPUT: string;
export declare const BUTTON_INPUT: "button";
export declare const SEARCH_INPUT: string;
export declare const POSITIONS: {
    LEFT: string;
    TOP: string;
    RIGHT: string;
    BOTTOM: string;
};
export declare const TYPENAME = "__typename";
export declare const ID = "id";
export declare const DEFAULT_PAGE = 1;
export declare const DEFAULT_LIMIT = 10;
export declare const ASC_SORT = "ASC";
export declare const DESC_SORT = "DESC";
